### ISSUE TITLE
hostapd workarounds needed not just for ubuntu

### ISSUE THREAD

**Issue by aurabindo** [prahladyeri/hotspotd#12]
I tried on both fedora 21 and archlinux. Both require the wifi to be turned off by nmcli and then unblocked by rfkill. And the command line has changed for nmcli in these newer distros.

So please add a check for the nmcli version. If its the new one, do `nmcli r w off`. You can possibly remove the check for ubuntu.

**Comment by aurabindo** [comment]
`nmcli radio wifi radio off` is incorrect. It should be `nmcli radio wifi off` 

A typo ? :P

**Comment by prahladyeri** [comment]
> A typo ? :P 

Yup. Sorry abt that. I've fixed it and rebuilt.
Please test and confirm whether its working.

**Comment by prahladyeri** [comment]
Closing this bug, since there is no news for a long time.
