### ISSUE TITLE
configure wizard: wrong interface id in run.conf

### ISSUE THREAD

**Issue by aurabindo** [prahladyeri/hotspotd#13]
On systems other than ubuntu, the interface is not `wlan0`. In archlinux, it is `wlo1` and something else in fedora. This id is not properly saved by the configure wizard. It is always `wlan0`. This triggers a silent failure; when `start` is invoked without `-v` it still says hotspot started, without any error text.

**Comment by prahladyeri** [comment]
I haven't got around testing this for a while. Today, I'll test this on a few distro`s I've got including the latest versions of debian and fedora.
