### ISSUE TITLE
Block access

### ISSUE THREAD

**Issue by denisKaranja** [prahladyeri/hotspotd#14]
Hi @prahladyeri , is there a way one can block a certain device using the MAC addr from accessing your hotspot?

**Comment by prahladyeri** [comment]
@denisKaranja There isn't any built-in way. But I guess, you can mod the python script to make a call to a hostapd API that might fetch you the connected MAC address. Need to read up the kernel docs on hostapd for that:

https://wireless.wiki.kernel.org/en/users/documentation/hostapd

**Comment by denisKaranja** [comment]
Thanks @prahladyeri . Doing that asap. Thanks for the great app too :100:
