### ISSUE TITLE
Error during install v0.1.5

### ISSUE THREAD

**Issue by aossey** [prahladyeri/hotspotd#15]
I get the following error when I run install on CentOS 5.11.  Looks like it should be 'run.dat' but I can't find where this is referenced in the code.

running install
running build
running build_py
creating build
creating build/lib
creating build/lib/hotspotd
copying __init__.py -> build/lib/hotspotd
copying cli.py -> build/lib/hotspotd
copying main.py -> build/lib/hotspotd
**error: can't copy 'un.dat': doesn't exist or not a regular file**

**Comment by prahladyeri** [comment]
@aossey Sorry for the delay, for some weird reason I've stopped getting email notifications for bug raised here. The `run.dat` is just a template configuration file for hostapd. It is later used to create the actual config file based on your SSID, etc. This should be in the same location as main.py

**Comment by prahladyeri** [comment]
@aossey I'm closing this issue. Let me know if you face any issues and I'll reopen it.
