### ISSUE TITLE
Does not work in Linux mint 17.1 64-bit

### ISSUE THREAD

**Issue by Xunius** [prahladyeri/hotspotd#18]
Hello,
I've tested your software in my Linux Mint 17.1 machine but it does not seem to work properly.
The installation went smoothly, and I set up a hotspot using `sudo hotspotd start` and entered necessary info. The outputs suggest that hotspot is running, but it is not visible to any devices. I tried to connect to that in my iphone but it says not reachable.

**Comment by andretnt** [comment]
Same here in Linux Mint 17.1 32 bits!!!

**Comment by prahladyeri** [comment]
@andretnt  - Have you made sure that a firewall is not blocking your iphone from connecting?
