### ISSUE TITLE
Doesn't work in Ubuntu 15.04 64bit

### ISSUE THREAD

**Issue by rajmani1995** [prahladyeri/hotspotd#20]
Hi,
I used this package to use wifi hotspot in Ubuntu 14.04 it was working fine, but after upgrading to 15.04 it doesn't seem work properly.
```
sudo hotspotd start
````
is running. but wifi signal is not there.
I used hotspotd-0.1.4 version

**Comment by prahladyeri** [comment]
Try reinstalling the `hostapd` package. It is a critical dependency and while you upgraded, it might have had some issues. Just do:

    sudo apt-get remove hostapd
    sudo apt-get install hostapd

**Comment by rajmani1995** [comment]
Thanks. It Worked !!

**Comment by prahladyeri** [comment]
You are welcome!
