### ISSUE TITLE
"Wireless interface could not be found on your device."

### ISSUE THREAD

**Issue by Shtampzor** [prahladyeri/hotspotd#26]
Hello,
I use a USB WiFI dongle, but when I run hotspotd it says this:
Verifying connections
Wireless interface could not be found on your device.
Traceback (most recent call last):
  File "/usr/local/bin/hotspotd", line 22, in <module>
    hotspotd.main.main(args)
  File "/usr/local/lib/python2.7/dist-packages/hotspotd/main.py", line 308, in main
    dc =json.load(open('hotspotd.json'))
IOError: [Errno 2] No such file or directory: 'hotspotd.json'

WiFi is enabled and I can see other WiFI networks.

**Comment by prahladyeri** [comment]
What is the output of `ifconfig`? Does it show any wireless interface? Also make sure that the said wifi is enabled using `rflist`.

**Comment by Shtampzor** [comment]
`ifconfig` shows enp3s0, lo and wlx60e327172ffd.
`rfkill list` doesn't show anything.

**Comment by prahladyeri** [comment]
Looks like you do have a wireless card, but rfkill is not showing it which is strange. Its quite probable that you need to add additional drivers to get your wifi working. What distro is it? Also run `iwconfig`, what it says?

For [reference](http://askubuntu.com/questions/510642/rfkill-list-all-shows-nothing-in-command-line)

**Comment by prahladyeri** [comment]
In case you are using an RALink Wifi Adapter, I think these two links might help you as well (and also try upgrading your kernel first):

http://ubuntuforums.org/showthread.php?t=2104690
askubuntu.com/questions/656633/14-04-ralink-rt3290sta-doesnt-work-doesnt-perform-make-from-the-popular-sol

**Comment by Shtampzor** [comment]
I found the drivers, but it says that they are for kernel version 2.6.18 ~ 3.19.3, and mine is 4.2.0
I'm using Kubuntu 15.10.
`iwconfig` shows the same three items.
My adapter is Realtek.

**Comment by prahladyeri** [comment]
Hmmn. Looks like either you will have to install an older distro, or try and find some solution online.

Can you post the `iwconfig` output? There is a good chance others have also faced this issue and Google might find something on this.

**Comment by Shtampzor** [comment]
Maybe I can try to install the drivers anyways? Or it won't work for sure?
The `iwconfig` output is:
enp3s0    no wireless extensions.

wlx60e327172ffd  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

**Comment by prahladyeri** [comment]
What model is the wifi card? In case it is RTL8192, read [this](http://www.linuxquestions.org/questions/linux-wireless-networking-41/rtl8192-wifi-loaded-driver-but-unknown-next-step-912394/) link. You might have to install this [non-free firmware](https://wiki.debian.org/rtl819x).

**Comment by Shtampzor** [comment]
The dongle's model is TL-WN725N V2.

**Comment by prahladyeri** [comment]
[Here](http://askubuntu.com/a/297168/49938) is the exact solution that should work for you, try it and let me know.

**Comment by Shtampzor** [comment]
I did what it said, there were no 404s for the git files, copied the .bin to /lib/firmware/rtlwifi/ and rebooted, but it still doesn't work.

**Comment by prahladyeri** [comment]
There is another answer above that, try that too and if it still isn't resolved, raise a fresh issue on askubuntu.com:

> Yes, Tim Phillips has produced a great solution to this problem. See this thread http://ubuntuforums.org/showthread.php?t=2092934&page=2&highlight=8188CUs

> Tim has made available a .deb file that fixes the 13.04 installation bug and included a dkms fix so it's no longer necessary to recompile after each kernel upgrade. Here's a link to the .deb file: https://code.google.com/p/realtek-8188cus-wireless-drivers-3444749-ubuntu-1304/

**Comment by dammianhr** [comment]
hi!
i have the same problem:

Verifying connections
Wireless interface could not be found on your device.
Traceback (most recent call last):
  File "/usr/local/bin/hotspotd", line 22, in <module>
    hotspotd.main.main(args)
  File "/usr/local/lib/python2.7/dist-packages/hotspotd/main.py", line 310, in main
    dc =json.load(open('hotspotd.json'))
IOError: [Errno 2] No such file or directory: 'hotspotd.json'

iwconfig
wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

in raspberry pi 2.
Linux raspberrypi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux

**Comment by noraj** [comment]
```
$ sudo hotspotd start
[sudo] password for noraj: 
Verifying connections
Wireless interface could not be found on your device.
Traceback (most recent call last):
  File "/bin/hotspotd", line 22, in <module>
    hotspotd.main.main(args)
  File "/usr/lib/python2.7/site-packages/hotspotd/main.py", line 310, in main
    dc =json.load(open('hotspotd.json'))
IOError: [Errno 2] No such file or directory: 'hotspotd.json'
```

```
$ ip a | grep w
4: wlo1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
6: wwp0s20u6c3: <BROADCAST,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
```

```
$ rfkill list
0: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
1: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
```

```
$ lspci -k | grep -A 3 -i network 
03:00.0 Network controller: Intel Corporation Wireless 7265 (rev 48)
        DeviceName: WLAN
        Subsystem: Intel Corporation Dual Band Wireless-AC 7265
        Kernel driver in use: iwlwifi
```

```
$ dmesg | grep iwlwif
[   13.943321] iwlwifi 0000:03:00.0: enabling device (0000 -> 0002)
[   13.962079] iwlwifi 0000:03:00.0: loaded firmware version 17.948900127.0 op_mode iwlmvm
[   14.088239] iwlwifi 0000:03:00.0: Detected Intel(R) Dual Band Wireless AC 7265, REV=0x184
[   14.107045] iwlwifi 0000:03:00.0: base HW address: 64:80:99:eb:61:7b
[   14.613895] iwlwifi 0000:03:00.0 wlo1: renamed from wlan0
```

**Comment by noraj** [comment]
@prahladyeri The failure is not from drivers but from the code. 

https://github.com/prahladyeri/hotspotd/blob/682602639fdaa342b2749d34c12254f9d98a9981/main.py#L44

https://github.com/prahladyeri/hotspotd/blob/682602639fdaa342b2749d34c12254f9d98a9981/main.py#L56

Both of this command won't be used on any arch based distros because they are deprecated (using ip instead).

Instead of parsing the output of a command that will very on many distros, a more portable approach is to parse `/proc/net/dev` or list what is in `/sys/class/net/`. Or using a python package such as [`netifaces`](https://github.com/al45tair/netifaces).

**Comment by prahladyeri** [comment]
@noraj The problem with `ip addr` command is that there isn't enough information to determine whether its a wifi or ethernet card:

    wlp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000

In contrast, `iwconfig` has the exact string that helps to know if its a wifi card:

    IEEE 802.11

Even if the commands are depreciated on arch, they should still be installed there as a legacy or at least compatibility - since popular distros like ubuntu and debian have them.

**Comment by noraj** [comment]
@prahladyeri I don't agree at all.

> Even if the iwconfig command is depreciated on arch, they should still be installed there as a legacy or at least compatibility - since popular distros like ubuntu and debian have them.

With this kind of thinking, nothing could change. And it's not deprecated **for arch**, it is deprecated. That's just that debian make a release every 4 years so they have always old and deprecated stuff, this distro is designed only for retro-compatibility purpose and supporting exotic architecture, using it on a desktop is a non-sense.

> The problem with `ip addr` command is that there isn't enough information to determine whether its a wifi or ethernet card:

That's not true. No matter the way you use (ip addr, ifconfig, iwconfig, ... or parsing /proc/net/dev or /sys/class/net), `enp37s0` the first `e` is for **ethernet** and `wlp6s0` the first `w` is for wireless.

---

As I said before spawning and parsing a command output (even `ip addrd`) is not a good idea anyway.
A better one is to parse `/proc/net/dev` or list what is in `/sys/class/net/`.
Or there are other solutions as well [Get Wi-Fi interface device names](https://unix.stackexchange.com/questions/286721/get-wi-fi-interface-device-names), using `iw dev` or `/proc/net/wireless` or `find` and `/sys/class/net`.

But keep in mind that:

- Spawning a command is worse than reading a file
- Using deprecated commands will break a lot of compatibility

If you don't want to change your tool at least put in the README that this tool is working only for ubuntu/debian. But all other distros won't change for your tool.

**Comment by noraj** [comment]
For everyone that can't use this tool, use https://github.com/oblique/create_ap instead it is better coded, more maintained, more available, more compatible and more famous. And it has more features.
