### ISSUE TITLE
no internet access via wifi in kali linux rolling

### ISSUE THREAD

**Issue by hudiya** [prahladyeri/hotspotd#32]
ii already use any way to fix it ,but no one can solve permanently

**Comment by prahladyeri** [comment]
Can you please specify the issue in more detail? How to replicate it and what error messages are printed on the console?

**Comment by tycoon420** [comment]
i had the same issue on kali rolling. 
so i rollbacked to kali sana its working like a charm.Something is wrong in kali rolling files i guess
