### ISSUE TITLE
Serving content

### ISSUE THREAD

**Issue by ghost** [prahladyeri/hotspotd#35]
When people use the hotspot can I serve content over it ?

**Comment by prahladyeri** [comment]
If you have apache or nginx web server running on the same server as hotspotd, then sure you can. The hotspotd is also a node in the entire DHCP address range, so it can be accessed through any device.

All you have to do is make the web-server listen on all ports and keep your firewall open on ports 80 and 443 (or whatever ports you want to serve content on).
