### ISSUE TITLE
No such file or directory: 'VERSION'

### ISSUE THREAD

**Issue by duoduoeeee** [prahladyeri/hotspotd#36]
I installed a proprietary driver in my Ubuntu 16.10 device. My wireless card is `03:00.0 Network controller: Broadcom Limited BCM4313 802.11bgn Wireless Network Adapter (rev 01)`
I ran `lspci -k | grep -A 3 -i network` and it says
```
03:00.0 Network controller: Broadcom Limited BCM4313 802.11bgn Wireless Network Adapter (rev 01)
	Subsystem: Broadcom Limited BCM4313 802.11bgn Wireless Network Adapter
	Kernel driver in use: wl
	Kernel modules: bcma, wl
```
So I ran `modinfo wl | grep depend` and it says
```
depends:        cfg80211
```
I ran `sudo hotspotd start` it output something like these below. I believe there's something wrong with hotspotd itself:
```
Traceback (most recent call last):
  File "/usr/local/bin/hotspotd", line 28, in <module>
    mainmod.main(args)
  File "/usr/local/lib/python2.7/dist-packages/hotspotd/main.py", line 291, in main
    the_version = open("VERSION").read().strip()
IOError: [Errno 2] No such file or directory: 'VERSION'
```
So what happened?

BTW bcma doesn't support the 80211 stuff. It says `depends:` and that is all.

**Comment by duoduoeeee** [comment]
OK I found that cfg80211 is different from mac80211
Please close this issue.

**Comment by prahladyeri** [comment]
> OK I found that cfg80211 is different from mac80211

Whilst that is certainly true, your error regarding version doesn't seem to be about that. Are you sure the setup ran without any problems? In any case, you can create a text file called VERSION and manually place it in following directory and see if this error resolves:

`/usr/local/lib/python2.7/dist-packages/hotspotd/`

**Comment by duoduoeeee** [comment]
oh sorry... I have just switched back to windows thus unable to try it out
but I believe creating the VERSION file as you said would (theoretically) fix the problem...
