### ISSUE TITLE
prompts "not installed" after succesfull installation on sbc

### ISSUE THREAD

**Issue by Sarverott** [prahladyeri/hotspotd#45]
# DETAILS
system: dietpi
sbc: orange pi lite
there is dedicated wifi-hotspot software in dietpi-software, but from unknow reasons it can't find repository of  it. Hotspotd installed succesfully, but it still think that it is not  #installed
# COPY OF CONSOLE LOG
**root@sbc:/path/hotspotd-0.1.4#** sudo hotspotd configure
_Verifying connections
Wifi interface found: wlan0
No network nic could be found on your deivce to interface with the LAN
Enter an IP address for your ap [192.168.45.1] :
Enter SSID [joe_ssid] :
Enter 10 digit password [1234567890] :
created hostapd configuration: run.conf
{'wlan': 'wlan0', 'SSID': 'joe_ssid', 'ip': '192.168.45.1', 'netmask': '255.255.255.0', 'password': '1234567890', 'inet': ''}
Configuration saved_
**root@sbc:/path/hotspotd-0.1.4#** sudo hotspotd configure
_Verifying connections
Wifi interface found: wlan0
No network nic could be found on your deivce to interface with the LAN
Enter an IP address for your ap [192.168.45.1] :
Enter SSID [joe_ssid] :montesque
Enter 10 digit password [1234567890] :KRACKcity874!
created hostapd configuration: run.conf
{'wlan': 'wlan0', 'SSID': 'montesque', 'ip': '192.168.45.1', 'netmask': '255.255.255.0', 'password': 'KRACKcity874!', 'inet': ''}
Configuration saved_
**root@sbc:/path/hotspotd-0.1.4#** sudo hotspotd start
**_hostapd executable not found. Make sure you have installed hostapd._**
**root@sbc:/path/hotspotd-0.1.4#** python setup.py install
_running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/hotspotd to 755
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/hotspotd-0.1.4.egg-info
Writing /usr/local/lib/python2.7/dist-packages/hotspotd-0.1.4.egg-info_
**root@sbc:/path/hotspotd-0.1.4#** hotspotd configure
_Verifying connections
Wifi interface found: wlan0
No network nic could be found on your deivce to interface with the LAN
Enter an IP address for your ap [192.168.45.1] :
Enter SSID [joe_ssid] :zaq12wsxcde3
Enter 10 digit password [1234567890] :1234567890wertyuiop
created hostapd configuration: run.conf
{'wlan': 'wlan0', 'SSID': 'zaq12wsxcde3', 'ip': '192.168.45.1', 'netmask': '255.255.255.0', 'password': '1234567890wertyuiop', 'inet': ''}
Configuration saved_
**root@sbc:/path/hotspotd-0.1.4#** hotspotd start
**_hostapd executable not found. Make sure you have installed  hostapd._**
**root@sbc:/path/hotspotd-0.1.4#** python hotspotd configure
_Verifying connections
Wifi interface found: wlan0
No network nic could be found on your deivce to interface with the LAN
Enter an IP address for your ap [192.168.45.1] :
Enter SSID [joe_ssid] :raressid
Enter 10 digit password [1234567890] :secret_pass
created hostapd configuration: run.conf
{'wlan': 'wlan0', 'SSID': 'raressid', 'ip': '192.168.45.1', 'netmask': '255.255.255.0', 'password': 'secret_pass', 'inet': ''}
Configuration saved_
**root@sbc:/path/hotspotd-0.1.4#** python hotspotd start
**_hostapd executable not found. Make sure you have installed hostapd._**
**root@sbc:/path/hotspotd-0.1.4#** cd ..
**root@sbc:/path#** python hotspotd start
_python: can't open file 'hotspotd': [Errno 2] No such file or directory_
**root@sbc:/path#** hotspotd start
**_hostapd executable not found. Make sure you have installed hostapd._**
**root@sbc:/path#** what's your problem?

**Comment by prahladyeri** [comment]
It only means that the underlying `hostapd` component couldn't be found on your linux machine. Try running `which hostapd` to locate the executable, and install the package if necessary. This program (`hotspotd`) depends on it.

**Comment by psachin** [comment]
@Sarverott 

1. Looks like configuration was not able to detect the interface which connect to the "internet" as 'inet' value is empty
```
 No network nic could be found on your deivce to interface with the LAN
```
and
```
{'wlan': 'wlan0', 'SSID': 'zaq12wsxcde3', 'ip': '192.168.45.1', 'netmask': '255.255.255.0', 'password': '1234567890wertyuiop', 'inet': ''}
```

2. You also need to find a way to install `hostapd` on Orange Pi
3. I see that a binary is placed under ` /usr/local/bin/hotspotd`. Can you try,
```
python /usr/loca/bin/hotspotd start
```
