### ISSUE TITLE
Refactored version available

### ISSUE THREAD

**Issue by psachin** [prahladyeri/hotspotd#47]
Hello @prahladyeri 

In an attempt to run it on Slackware GNU/Linux I refactored it. I'am quite happy with it. The changes and can be found here https://github.com/psachin/hotspotd

Let me know your view so that I start sending you changes.

**Comment by prahladyeri** [comment]
What exactly have you changed?

**Comment by prahladyeri** [comment]
I've stopped maintaining this project since many years. I can see there are some forks generated over time, try raising this issue on one of those.
