### ISSUE TITLE
Slave Raspberry Pi with Arduino

### ISSUE THREAD

**Issue by KaiserEd** [prahladyeri/hotspotd#48]
Hi everyone! I've been searching the internet about "slaving raspi with arduino" but I did not get any answer. All I see is "slave arduino with raspi". Does anyone here knows how to execute a python code on raspi using arduino via serial monitor? I am looking on how arduino send commands on serial monitor then to be executed by raspi.
Any comments and suggestions would be helpful.

Thank you and more power.

Sir! I am sorry I accidentally post this in here and I don't know how to transfer this post to where it belongs.

**Comment by prahladyeri** [comment]
Not pertaining to the topic.
