### ISSUE TITLE
Works very well! [Adding basic web server]

### ISSUE THREAD

**Issue by nadavb** [prahladyeri/hotspotd#49]
Wow! hotspotd works out of the box (I tried it on Dragonboard 410c). Very nice.

Now a question - what's the right way to add a simple web server, so when a I browse from my phone to any url, a default web page will be shown? (This will be used for the wifi provisioning of the device)

**Comment by prahladyeri** [comment]
Thanks a lot!

No, I don't think a web-interface can be easily added as the access point works through NAT forwarding using `iptables`.

It has been a long time since I had a look at the code, though. Once I get some time, I'll review it again and you know if some way to achieve this.

**Comment by nadavb** [comment]
Thanks. Once the device is connected to the AP we just created using hotspotd, why should it be complicated to simply listen to incoming TCP requests, like a regular web server, and answer them?

If I install a simple web server, wouldn't it be easy?

**Comment by nadavb** [comment]
Btw - I just installed Apache (web server) and it worked out of the box, so hotspod + apache can help doing the provisioning screen easily. (The captive portal)

**Comment by prahladyeri** [comment]
I'm closing this since its a long time, reopen a new case if you are still using hotspotd and have this issue.
