### ISSUE TITLE
Does it work on Ubuntu 18.04?

### ISSUE THREAD

**Issue by naumanafsar** [prahladyeri/hotspotd#52]
I successfully installed everything on my Ubuntu 18.04 but i am unable to connect my android phone with the hotspot created with the hotspotd.
Well, i can't even see my hotspotd ssid on my phone, i tried "Add Network" thought it maybe a hidden network, but that doesn't work either!

Help Please!

**Comment by prahladyeri** [comment]
Its not a hidden network, the problem should be on the server. Is `hotspotd` even started on the server, if so what message is seen on the console?

**Comment by naumanafsar** [comment]
When i start hostapd, it says ```Verifying interfaces
done.
created interface: mon.wlp2s0 on IP: 192.168.8.100
wait..
enabling forward in sysctl.
net.ipv4.ip_forward = 1
creating NAT using iptables: wlp2s0<->enp1s0:
running dnsmasq
hotspot is running.
```

**Comment by prahladyeri** [comment]
I'm closing since its a very long time, raise a new issue if you are still using hotspotd and facing this issue.
