### ISSUE TITLE
Hotspot not being detected by android phone

### ISSUE THREAD

**Issue by shreyasaha1997** [prahladyeri/hotspotd#53]
sudo hotspotd command is working all fine. My wifi card supports the AP mode as well. However, I cannot see the hotspot name on my android phone. Can you tell me where I am going wrong?

**Comment by prahladyeri** [comment]
Its probably got something to do with your phone, try to rescan on multiple devices. If the issue still occurs, let me know the console output of `hotspotd` when you start it.

**Comment by shreyasaha1997** [comment]
Other phones are not able to detect the wifi as well. My laptop doesn't have a wired internet connection. Its connected to JioFi. I read that in case your laptop is connected to a wireless network, it cant be connected to the internet as well as support a hotspot at the same time. So, do you think I should try using a LAN cable?

My console outputs are as follows:

shreya@shreya-Inspiron-3543:~/Desktop/hotspotd-0.1.6$ sudo python setup.py install

running install
running build
running build_py
running build_scripts
running install_lib
creating /usr/local/lib/python2.7/dist-packages/hotspotd
copying build/lib.linux-i686-2.7/hotspotd/run.dat -> /usr/local/lib/python2.7/dist-packages/hotspotd
copying build/lib.linux-i686-2.7/hotspotd/__init__.py -> /usr/local/lib/python2.7/dist-packages/hotspotd
copying build/lib.linux-i686-2.7/hotspotd/cli.py -> /usr/local/lib/python2.7/dist-packages/hotspotd
copying build/lib.linux-i686-2.7/hotspotd/main.py -> /usr/local/lib/python2.7/dist-packages/hotspotd
byte-compiling /usr/local/lib/python2.7/dist-packages/hotspotd/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/hotspotd/cli.py to cli.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/hotspotd/main.py to main.pyc
running install_scripts
copying build/scripts-2.7/hotspotd -> /usr/local/bin
changing mode of /usr/local/bin/hotspotd to 775
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/hotspotd-0.1.6.egg-info
Writing /usr/local/lib/python2.7/dist-packages/hotspotd-0.1.6.egg-info

shreya@shreya-Inspiron-3543:~/Desktop/hotspotd-0.1.6$ sudo hotspotd start

Verifying connections
Wifi interface found: wlp6s0
Network interface found: enp7s0
Enter an IP address for your ap [192.168.45.1] :127.0.0.1
Enter SSID [joe_ssid] :blabla
Enter 10 digit password [1234567890] :1234567890
created hostapd configuration: run.conf
{'wlan': 'wlp6s0', 'SSID': 'blabla', 'ip': '127.0.0.1', 'netmask': '255.255.255.0', 'password': '1234567890', 'inet': 'enp7s0'}
Configuration saved
Verifying interfaces
done.
done.
created interface: mon.wlp6s0 on IP: 127.0.0.1
wait..
stopping dnsmasq
enabling forward in sysctl.
net.ipv4.ip_forward = 1
creating NAT using iptables: wlp6s0<->enp7s0
running dnsmasq
dnsmasq --dhcp-authoritative --interface=wlp6s0 --dhcp-range=127.0.0.20,127.0.0.100,255.255.255.0,4h
hostapd -B /usr/local/lib/python2.7/dist-packages/hotspotd/run.conf
hotspot is running.

**Comment by prahladyeri** [comment]
> I read that in case your laptop is connected to a wireless network, it cant be connected to the internet as well as support a hotspot at the same time.

That's not necessary, you can use the same device to create multiple virtual connections, one connecting to the jiofi interface and another connecting to your local WLAN. However, you need to make sure that `hotspotd` is configured properly (the jiofi and local wifi connections are identified as such):

    Wifi interface found: wlp6s0
    Network interface found: enp7s0

As per your logs, this is how `hotspotd` has identified the connections by default, it assumes that  `enp7s0` is your jiofi connection (`Network Interface found`) and `wlp6s0` is your local wifi connection (`Wifi interface found`). However, if that detection was wrong, it may not work, and you'll have to swap the values of those properties (`inet` and `wlan` respectively)  in the configuration file (`run.conf`).

You can determine which interface is the jiofi connection by running the `ifconfig` command. There will be a list of interfaces followed by various details about them. At the end of each detail, there will be two values called `RX bytes` and `TX bytes` that represent the amount of data uploaded/downloaded. You can usually look at them and tell which belongs to the internet or local wifi connection.
