### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by shreyasaha1997** [prahladyeri/hotspotd#54]
Is there anyway in which we can see the mac address of device when it is trying to connect to my wifi and ask the device for additional details? Can we block certain mac addresses using hotspotd?

**Comment by prahladyeri** [comment]
You'll have to look into the man page of [dns-masq](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html). As you can see in main.py code (line 223), our app is just delegating the DNS part to `dnsmasq` which assigns the IP addresses to your connected clients:

	#start dnsmasq
	s = 'dnsmasq --dhcp-authoritative --interface=' + wlan + ' --dhcp-range=' + ipparts + '.20,' + ipparts +'.100,' + Netmask + ',4h'
	print 'running dnsmasq'
	print s
	r = cli.execute_shell(s)
	cli.writelog(r)

As the linked page suggests, there are options like `--log-dhcp` which creates logs for connections and you can read this log file to make out which mac addresses are connected. As for blocking based on mac addresses, you can do that using [iptables](https://serverfault.com/questions/578013/linux-iptables-drop-traffic-based-on-mac-address)

**Comment by shreyasaha1997** [comment]
Thanks a lot. One more thing, can you suggest what should I do for the following:

I want to send and receive some additional details from a device before I allow it to access internet using my hotspot. Is it possible?

**Comment by prahladyeri** [comment]
I'm afraid not! If you see the `main.py` code, all we are doing is creating a low-level NAT bridge using `iptables` between the client interface and the online (internet) interface:

	print 'creating NAT using iptables: ' + wlan + '<->' + ppp
	cli.execute_shell('iptables -P FORWARD ACCEPT')
	
	#add iptables rules to create the NAT.
	cli.execute_shell('iptables --table nat --delete-chain')
	cli.execute_shell('iptables --table nat -F')
	r=cli.execute_shell('iptables --table nat -X')
	if len(r.strip())>0: print r.strip()
	cli.execute_shell('iptables -t nat -A POSTROUTING -o ' + ppp +  ' -j MASQUERADE')
	cli.execute_shell('iptables -A FORWARD -i ' + ppp + ' -o ' + wlan + ' -j ACCEPT -m state --state RELATED,ESTABLISHED')
	cli.execute_shell('iptables -A FORWARD -i ' + wlan + ' -o ' + ppp + ' -j ACCEPT')

**Comment by shreyasaha1997** [comment]
All right thanks again and just one last thing. Is the following possible?

A device is connected to my hotspot and is allotted an ip address but is not allowed to access the internet yet. Can I allow it to access the internet only after a TCP/UDP communication between the device and the my device that is running hotspotd?

**Comment by prahladyeri** [comment]
Most Welcome! Problem here is that our app isn't doing much on the listening and ip allocation part, all it does is delegate to `dnsmasq` for ip allocation and `iptables` for NAT forwarding, our app isn't even in the picture when the device actually gets connected to the hotspot.

For what you want to achieve, NAT isn't a good idea, but you'll have to research into something called proxy servers:

- [Squid - Proxy Server - Official Ubuntu Documentation](https://help.ubuntu.com/lts/serverguide/squid.html.en)
- [How To Set Up A Proxy Server In Ubuntu Linux](https://www.makeuseof.com/tag/set-proxy-server-ubuntu-linux/)

**Comment by shreyasaha1997** [comment]
I have a doubt. Just want to know if it works or not. Say I have created two dhcp ranges using dnsmasq. Say the first range is from 192.168.45.20-40 and the second range is from 192.168.45.60-80. The first scope does not allow default gateway to the internet, the devices can only communicate with each other using TCP/UDP. The second scope allows access to the internet. Now, say a device is first allocated an IP address in the first scope. After connection, it changes its IP address to the second scope. Will it have access to the internet?
