### ISSUE TITLE
Not an issue, a doubt

### ISSUE THREAD

**Issue by shreyasaha1997** [prahladyeri/hotspotd#57]
I have a doubt. Just want to know if it works or not. Say I have created two dhcp ranges using dnsmasq. Say the first range is from 192.168.45.20-40 and the second range is from 192.168.45.60-80. The first scope does not allow default gateway to the internet, the devices can only communicate with each other using TCP/UDP. The second scope allows access to the internet. Now, say a device is first allocated an IP address in the first scope. After connection, it changes its IP address to the second scope. Will it have access to the internet?

**Comment by prahladyeri** [comment]
I've stopped maintaining this project since many years. I can see there are some forks generated over time, try raising this issue on one of those.
