### ISSUE TITLE
Edit the source code

### ISSUE THREAD

**Issue by mohammed1997010** [prahladyeri/hotspotd#58]
hi...
I need to Edit the source code so when any one try to connect to the hotspot
and use a password  I want to print the password which he/she used to connect to my hotspot
(I want to get the variable password and print it when any one try to connect to the hotspot)
thanx <)

**Comment by prahladyeri** [comment]
If you setup using the tarball, then the source should be on your usual PYTHON path where the libraries are typically installed. On Linux, this is usually this:

    /usr/lib/python2.7/dist-packages/setuptools

And on windows, it is this:

    `C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python<ver>\\lib\\test`

Hope that helps.

**Comment by mohammed1997010** [comment]
thank you...
I have another question plz...
in the source code what is the variable name which containing the password that the user used it t connect to my hotspot
I want the tool to print it for me
thank you
