### ISSUE TITLE
Permission denied !!

### ISSUE THREAD

**Issue by materoy** [prahladyeri/hotspotd#59]
Requires extra priviledges to create a directory in linux /etc dir 

   os.makedirs(self.root_directory)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/etc/accesspoint/'

**Comment by prahladyeri** [comment]
I've stopped maintaining this project since many years. I can see there are some forks generated over time, try raising this issue on one of those.
